/*
 * RaceTemp_config.h
 *
 * Project-local RaceTemp configuration.
 */

#ifndef RACETEMP_CONFIG_H_
#define RACETEMP_CONFIG_H_

#define RACETEMP_THERMOCOUPLE_IC_MAX31855  1
#define RACETEMP_THERMOCOUPLE_IC_MAX31856  2

#define RACETEMP_THERMOCOUPLE_IC RACETEMP_THERMOCOUPLE_IC_MAX31856
#ifndef RACETEMP_THERMOCOUPLE_IC
#define RACETEMP_THERMOCOUPLE_IC RACETEMP_THERMOCOUPLE_IC_MAX31855
#endif

#define RACETEMP_MAX31856_TC_TYPE_B 0x00
#define RACETEMP_MAX31856_TC_TYPE_E 0x01
#define RACETEMP_MAX31856_TC_TYPE_J 0x02
#define RACETEMP_MAX31856_TC_TYPE_K 0x03
#define RACETEMP_MAX31856_TC_TYPE_N 0x04
#define RACETEMP_MAX31856_TC_TYPE_R 0x05
#define RACETEMP_MAX31856_TC_TYPE_S 0x06
#define RACETEMP_MAX31856_TC_TYPE_T 0x07

#ifndef RACETEMP_MAX31856_TC_TYPE
#define RACETEMP_MAX31856_TC_TYPE RACETEMP_MAX31856_TC_TYPE_K
#endif

#ifndef RACETEMP_RPM_TIMER_HZ
#define RACETEMP_RPM_TIMER_HZ 16000000.0f
#endif

#ifndef RACETEMP_IGNITION_PULSES_PER_REV
#define RACETEMP_IGNITION_PULSES_PER_REV 1.0f
#endif

#ifndef RACETEMP_RPM_MAX
#define RACETEMP_RPM_MAX 20000.0f
#endif

#ifndef RACETEMP_RPM_MIN_PERIOD_TICKS
#define RACETEMP_RPM_MIN_PERIOD_TICKS ((uint32_t)((60.0f * RACETEMP_RPM_TIMER_HZ) / (RACETEMP_RPM_MAX * RACETEMP_IGNITION_PULSES_PER_REV)))
#endif

#ifndef RACETEMP_RPM_TIMEOUT_TICKS
#define RACETEMP_RPM_TIMEOUT_TICKS ((uint32_t)(2.0f * RACETEMP_RPM_TIMER_HZ))
#endif

#ifndef RACETEMP_ENGINE_REVS_PER_IGNITION_PULSE
#define RACETEMP_ENGINE_REVS_PER_IGNITION_PULSE 1U
#endif

#ifndef RACETEMP_COUNTER_FLASH_BASE
#define RACETEMP_COUNTER_FLASH_BASE 0x0807E000UL
#endif

#ifndef RACETEMP_COUNTER_FLASH_PAGES
#define RACETEMP_COUNTER_FLASH_PAGES 2U
#endif

#endif /* RACETEMP_CONFIG_H_ */
