/*
 * RaceTemp_config.h
 *
 * Project-local RaceTemp configuration.
 */

#ifndef RACETEMP_CONFIG_H_
#define RACETEMP_CONFIG_H_

#define RACETEMP_THERMOCOUPLE_IC_MAX31855  1
#define RACETEMP_THERMOCOUPLE_IC_MAX31856  2

#define RACETEMP_THERMOCOUPLE_IC RACETEMP_THERMOCOUPLE_IC_MAX31856
#ifndef RACETEMP_THERMOCOUPLE_IC
#define RACETEMP_THERMOCOUPLE_IC RACETEMP_THERMOCOUPLE_IC_MAX31855
#endif

#define RACETEMP_MAX31856_TC_TYPE_B 0x00
#define RACETEMP_MAX31856_TC_TYPE_E 0x01
#define RACETEMP_MAX31856_TC_TYPE_J 0x02
#define RACETEMP_MAX31856_TC_TYPE_K 0x03
#define RACETEMP_MAX31856_TC_TYPE_N 0x04
#define RACETEMP_MAX31856_TC_TYPE_R 0x05
#define RACETEMP_MAX31856_TC_TYPE_S 0x06
#define RACETEMP_MAX31856_TC_TYPE_T 0x07

#ifndef RACETEMP_MAX31856_TC_TYPE
#define RACETEMP_MAX31856_TC_TYPE RACETEMP_MAX31856_TC_TYPE_K
#endif

/* Signed 0.0625 deg C steps; calibrated for the currently fitted device. */
#ifndef RACETEMP_MAX31856_CJ_OFFSET_STEPS
#define RACETEMP_MAX31856_CJ_OFFSET_STEPS (-50)
#endif
#if (RACETEMP_MAX31856_CJ_OFFSET_STEPS < -128) || (RACETEMP_MAX31856_CJ_OFFSET_STEPS > 127)
#error "RACETEMP_MAX31856_CJ_OFFSET_STEPS must fit in a signed 8-bit CJTO register"
#endif

#ifndef RACETEMP_RPM_TIMER_HZ
#define RACETEMP_RPM_TIMER_HZ 16000000.0f
#endif

#ifndef RACETEMP_IGNITION_PULSES_PER_REV
#define RACETEMP_IGNITION_PULSES_PER_REV 1.0f
#endif

#ifndef RACETEMP_RPM_MAX
#define RACETEMP_RPM_MAX 20000.0f
#endif

#ifndef RACETEMP_RPM_MIN_PERIOD_TICKS
#define RACETEMP_RPM_MIN_PERIOD_TICKS ((uint32_t)((60.0f * RACETEMP_RPM_TIMER_HZ) / (RACETEMP_RPM_MAX * RACETEMP_IGNITION_PULSES_PER_REV)))
#endif

#ifndef RACETEMP_RPM_TIMEOUT_TICKS
#define RACETEMP_RPM_TIMEOUT_TICKS ((uint32_t)(2.0f * RACETEMP_RPM_TIMER_HZ))
#endif

#ifndef RACETEMP_RPM_ESTIMATOR_PERIODS
#define RACETEMP_RPM_ESTIMATOR_PERIODS 6U
#endif
#if (RACETEMP_RPM_ESTIMATOR_PERIODS < 2U) || (RACETEMP_RPM_ESTIMATOR_PERIODS > 8U)
#error "RACETEMP_RPM_ESTIMATOR_PERIODS must be between 2 and 8"
#endif

#ifndef RACETEMP_RPM_ESTIMATOR_MAX_WINDOW_TICKS
#define RACETEMP_RPM_ESTIMATOR_MAX_WINDOW_TICKS ((uint32_t)(0.080f * RACETEMP_RPM_TIMER_HZ))
#endif

#ifndef RACETEMP_FAST_TICK_HZ
#define RACETEMP_FAST_TICK_HZ 100U
#endif

#ifndef RACETEMP_RPM_FAST_PUBLISH_DIVIDER
#define RACETEMP_RPM_FAST_PUBLISH_DIVIDER 4U
#endif

#ifndef RACETEMP_SLOW_PUBLISH_DIVIDER
#define RACETEMP_SLOW_PUBLISH_DIVIDER 10U
#endif

#ifndef RACETEMP_PEAK_HOLD_TICKS
#define RACETEMP_PEAK_HOLD_TICKS ((uint32_t)(5.0f * RACETEMP_RPM_TIMER_HZ))
#endif

#ifndef RACETEMP_TC_RECOVERY_BAD_READS
#define RACETEMP_TC_RECOVERY_BAD_READS 3U
#endif

#ifndef RACETEMP_TC_POWER_RECOVERY_BAD_READS
#define RACETEMP_TC_POWER_RECOVERY_BAD_READS 10U
#endif

#ifndef RACETEMP_TC_POWER_CYCLE_DELAY_MS
#define RACETEMP_TC_POWER_CYCLE_DELAY_MS 10U
#endif

#ifndef RACETEMP_TC_INVALID_TEMPERATURE_C
#define RACETEMP_TC_INVALID_TEMPERATURE_C (0.0f)
#endif

#ifndef RACETEMP_TC_MIN_VALID_TEMPERATURE_C
#define RACETEMP_TC_MIN_VALID_TEMPERATURE_C (0.0f)
#endif

#ifndef RACETEMP_STATUS_LED_NORMAL_PERIOD_TICKS
#define RACETEMP_STATUS_LED_NORMAL_PERIOD_TICKS RACETEMP_FAST_TICK_HZ
#endif

#ifndef RACETEMP_STATUS_LED_NORMAL_ON_TICKS
#define RACETEMP_STATUS_LED_NORMAL_ON_TICKS 1U
#endif

#ifndef RACETEMP_STATUS_LED_FAULT_PERIOD_TICKS
#define RACETEMP_STATUS_LED_FAULT_PERIOD_TICKS (RACETEMP_FAST_TICK_HZ / 4U)
#endif

#ifndef RACETEMP_STATUS_LED_FAULT_ON_TICKS
#define RACETEMP_STATUS_LED_FAULT_ON_TICKS 2U
#endif

#ifndef RACETEMP_ENGINE_REVS_PER_IGNITION_PULSE
#define RACETEMP_ENGINE_REVS_PER_IGNITION_PULSE 1U
#endif

#ifndef RACETEMP_COUNTER_FLASH_BASE
/* Last two 4 KB flash pages. Keep this aligned with STM32WB55CGUX_FLASH.ld. */
#define RACETEMP_COUNTER_FLASH_BASE 0x0807E000UL
#endif

#ifndef RACETEMP_COUNTER_FLASH_PAGES
#define RACETEMP_COUNTER_FLASH_PAGES 2U
#endif

#endif /* RACETEMP_CONFIG_H_ */
